### ISSUE TITLE
GTF parsing error

### ISSUE THREAD

**Issue by wresch** [konrad/READemption#1]
the current gtf parser requires '=' separators between attribute name and value, which does not conform to the GTF spec.  here is a patch that will make it work with a relaxed gtf spec:

```diff
diff -ur reademptionlib/gff3.py reademptionlib/gff3.py
--- reademptionlib/gff3.py      2014-05-12 11:01:04.000000000 -0400
+++ reademptionlib/gff3.py      2015-06-04 10:28:28.091433000 -0400
@@ -1,4 +1,8 @@
 import csv
+import re
+
+# regular expression for parsing gff attributes correctly
+gff_attr_re = re.compile(r'(\S+)[ =]+"?([^";]+)"?;')
 
 class Gff3Parser(object):
     """
@@ -25,7 +29,6 @@
         return Gff3Entry(entry_dict)
 
 class Gff3Entry(object):
-
     def __init__(self, entry_dict):
         self.seq_id = entry_dict["seq_id"]
         self.source = entry_dict["source"]
@@ -45,11 +48,7 @@
         """Translate the attribute string to dictionary"""
         if attributes_string is None:
             return({})
-        if attributes_string.endswith(";"):
-            attributes_string = attributes_string[:-1]
-        return dict(
-                [key_value_pair.split("=") 
-                 for key_value_pair in attributes_string.split(";")])
+        return dict(gff_attr_re.findall(attributes_string))
 
     def __str__(self):
         return "\t".join([str(field) for field in [
```

**Comment by konrad** [comment]
Many thanks for your suggestion/patch, @wresch. Actually, this is not a bug but a feature. As the name of the class implies this is a GFF3 parser and the documentation also talks about annotation files in GFF3 format. GTF/GFF2 is considered as harmful/evil/inconsistent and should be not be further supported. Please have a look at [this](http://www.sequenceontology.org/gff3.shtml) for some explanation. Still, thanks for raising this issue and sending a patch! Please understand that I will not merge this into READemption due to the above mentioned reasons.

**Comment by wresch** [comment]
Hi,

yes i completely understand (and i agree about the format in principle).  I
guess I glanced over that part of the docs and got stuck with an
inscrutable traceback (see below) with a fresh ensembl annotation file that
took me a couple of hours to track down, so i decided that "quirks mode"
was preferable to principle if it saved others the same amount of time.
Maybe a readable error message instead of an exception for those of us
reading docs in a rush?

Anyway, I'm sorry if I sounded impolite.

mfg,
Wolfgang

Traceback (most recent call last):
  File "/usr/local/apps/Anaconda3/2.0.0/bin/reademption", line 4, in
<module>
    __import__('pkg_resources').run_script('READemption==0.3.6',
'reademption')
  File
"/usr/local/apps/Anaconda3/2.0.0/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/__init__.py",
line 729, in run_script
  File
"/usr/local/apps/Anaconda3/2.0.0/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/__init__.py",
line 1649, in run_script
  File
"/usr/local/apps/Anaconda3/2.0.0/lib/python3.4/site-packages/READemption-0.3.6-py3.4.egg/EGG-INFO/scripts/reademption",
line 283, in <module>
  File
"/usr/local/apps/Anaconda3/2.0.0/lib/python3.4/site-packages/READemption-0.3.6-py3.4.egg/EGG-INFO/scripts/reademption",
line 255, in main
  File
"/usr/local/apps/Anaconda3/2.0.0/lib/python3.4/site-packages/READemption-0.3.6-py3.4.egg/EGG-INFO/scripts/reademption",
line 269, in run_gene_wise_quantification
  File
"/spin1/sys/i386/usrlocal/apps/Anaconda3/2.0.0/lib/python3.4/site-packages/READemption-0.3.6-py3.4.egg/reademptionlib/controller.py",
line 624, in quantify_gene_wise
  File
"/spin1/sys/i386/usrlocal/apps/Anaconda3/2.0.0/lib/python3.4/site-packages/READemption-0.3.6-py3.4.egg/reademptionlib/controller.py",
line 589, in _check_job_completeness
ValueError: dictionary update sequence element #0 has length 1; 2 is
required

**Comment by konrad** [comment]
Thanks, Wolfgang. I completely agree - a proper, informative error message would be a helpful a this point. I will add this soon. Thanks for the suggestion!

Konrad

**Comment by konrad** [comment]
I added warning in the current version.

**Comment by wresch** [comment]
Great. Thanks
