### ISSUE TITLE
RNA-SEQ reads in the example not found

### ISSUE THREAD

**Issue by iseekwonderful** [konrad/READemption#6]
In the READemption [example](http://pythonhosted.org/READemption/example_analysis.html), the rna-seq example return 404 not found
```
$ wget -P READemption_analysis/input/reads http://reademptiondata.imib-zinf.net/InSPI2_R1.fa.bz2
$ wget -P READemption_analysis/input/reads http://reademptiondata.imib-zinf.net/InSPI2_R2.fa.bz2
$ wget -P READemption_analysis/input/reads http://reademptiondata.imib-zinf.net/LSP_R1.fa.bz2
$ wget -P READemption_analysis/input/reads http://reademptiondata.imib-zinf.net/LSP_R2.fa.bz2
```
could you please fix the download address or push these file to github?

Thanks
sheep

**Comment by konrad** [comment]
Thanks for pointing this out - I will take care of it and let you know when it is fixed.

**Comment by konrad** [comment]
The file are now online again. Sorry that this took so long, @iseekwonderful. Thanks for the feedback!

**Comment by iseekwonderful** [comment]
Thanks
